version: '3.4'

services:
  webweather:
    image: ${DOCKER_REGISTRY-}webweather
    build:
      context: .
      dockerfile: Dockerfile
    networks:
        - dockerlocal
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
    ports:
      - "5233:80"
      - "5234:443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro   
    depends_on:
     - postgres
  postgres:
    build:
        context: ./Images/postgres
    container_name: 'Postgres'
    hostname: local.postgres.ru
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
        - 5432:5432
    networks:
        - dockerlocal
networks:
  dockerlocal:
    name: dockerlocal
    driver: bridge
